# Generated by Django 2.1.7 on 2019-03-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(blank=True, max_length=30, null=True)),
                ('encrypted', models.CharField(blank=True, max_length=200, null=True)),
                ('decrypted', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemno', models.IntegerField(blank=True, db_column='Itemno', null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=20, null=True)),
                ('foodname', models.CharField(blank=True, db_column='FoodName', max_length=30, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
            ],
        ),
    ]
