# Generated by Django 2.1.7 on 2019-03-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='supermarket',
            options={'managed': False},
        ),
    ]
