# Generated by Django 2.1.7 on 2019-03-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_auto_20190321_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='play',
            table='play',
        ),
        migrations.AlterModelTable(
            name='supermarket',
            table='supermarket',
        ),
    ]
